development:
  adapter: redis
  url: redis://localhost:6379/3
  channel_prefix: user_list_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: user_list_production
